import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        "surface": "#000000",
        "surface-dim": "#000000",
        "surface-bright": "#0a0a0a",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#050505",
        "surface-container": "#080808",
        "surface-container-high": "#0d0d0d",
        "surface-container-highest": "#121212",
        "on-surface": "#dde5ff",
        "on-surface-variant": "#9eabcb",
        "inverse-surface": "#f9f9ff",
        "inverse-on-surface": "#4f5565",
        "outline": "#697593",
        "outline-variant": "#3c4863",
        "surface-tint": "#bed2ff",
        "on-primary": "#2b4778",
        "primary-container": "#a9c4fe",
        "on-primary-container": "#213d6f",
        "inverse-primary": "#445f92",
        "on-secondary": "#2e453b",
        "secondary-container": "#132a22",
        "on-secondary-container": "#91a99d",
        "tertiary": "#beffdb",
        "on-tertiary": "#006745",
        "tertiary-container": "#8cf8c3",
        "on-tertiary-container": "#005e3f",
        "error": "#ff716c",
        "on-error": "#490006",
        "error-container": "#8a1a1e",
        "on-error-container": "#ff9993",
        "primary-fixed": "#a9c4fe",
        "primary-fixed-dim": "#9cb6ef",
        "on-primary-fixed": "#062859",
        "on-primary-fixed-variant": "#2b4678",
        "secondary-fixed": "#ddf7e9",
        "secondary-fixed-dim": "#cee9db",
        "on-secondary-fixed": "#364d43",
        "on-secondary-fixed-variant": "#52695f",
        "tertiary-fixed": "#8cf8c3",
        "tertiary-fixed-dim": "#7de9b5",
        "on-tertiary-fixed": "#004930",
        "on-tertiary-fixed-variant": "#006947",
        "primary-dim": "#9cb6ef",
        "secondary-dim": "#a5bfb2",
        "tertiary-dim": "#7de9b5",
        "error-dim": "#c94947",
        "on-background": "#dde5ff",
        "surface-variant": "#19253f",
        "admin-mint": { DEFAULT: "#91F0B7", foreground: "#1A633F" },
        "admin-blue": { DEFAULT: "#ADBEFF", foreground: "#1E3A8A" },
        "admin-paleblue": { DEFAULT: "#C2D2FF", foreground: "#1E3A8A" },
        "admin-sage": { DEFAULT: "#ADC3B4", foreground: "#1A432F" },
        "admin-palemint": { DEFAULT: "#B4F5CC", foreground: "#165935" },
        "admin-coral": { DEFAULT: "#FF7B7B", foreground: "#8A1A1E" }
      },
      borderRadius: {
        "sm": "0.125rem",
        "DEFAULT": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "0.25rem",
        "base": "0.5rem",
        "sm": "0.75rem",
        "md": "1rem",
        "lg": "1.5rem",
        "xl": "2rem",
        "gutter": "1.5rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2rem"
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "title-md": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "display-lg": ["3.5rem", { lineHeight: "4rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["1.5rem", { lineHeight: "2rem", fontWeight: "600" }],
        "title-md": ["1.125rem", { lineHeight: "1.5rem", fontWeight: "500" }],
        "body-md": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.05em", fontWeight: "500" }]
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
