"""add name to org invite

Revision ID: 22e9491cdaee
Revises: c5b68a69b0a0
Create Date: 2026-09-03 13:23:19.068644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e9491cdaee'
down_revision: Union[str, Sequence[str], None] = 'c5b68a69b0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_credit_ledger_org_consume_ref'), table_name='credit_ledger', postgresql_where="(((type)::text = 'consume'::text) AND (reference_id IS NOT NULL))")
    op.add_column('organization_invites', sa.Column('name', sa.String(), nullable=True))
    op.drop_index(op.f('ix_quota_check_requests_held_expires'), table_name='quota_check_requests', postgresql_where="((status)::text = 'held'::text)")
    op.drop_index(op.f('uq_usage_ledger_org_request'), table_name='usage_ledger', postgresql_where='(request_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_usage_ledger_org_request'), 'usage_ledger', ['organization_id', 'request_id'], unique=True, postgresql_where='(request_id IS NOT NULL)')
    op.create_index(op.f('ix_quota_check_requests_held_expires'), 'quota_check_requests', ['expires_at'], unique=False, postgresql_where="((status)::text = 'held'::text)")
    op.drop_column('organization_invites', 'name')
    op.create_index(op.f('uq_credit_ledger_org_consume_ref'), 'credit_ledger', ['organization_id', 'reference_id'], unique=True, postgresql_where="(((type)::text = 'consume'::text) AND (reference_id IS NOT NULL))")
    # ### end Alembic commands ###
