"""create organization_entitlements

Revision ID: 807e3564c2ee
Revises: 852f4ac09824
Create Date: 2026-08-01 10:13:11.215428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '807e3564c2ee'
down_revision: Union[str, Sequence[str], None] = '852f4ac09824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_entitlements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_compute_units', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_entitlements_organization_id'), 'organization_entitlements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_entitlements_product_id'), 'organization_entitlements', ['product_id'], unique=False)
    # Data migration
    import uuid
    import datetime
    conn = op.get_bind()
    orgs = conn.execute(sa.text("SELECT id, entitlements FROM organizations")).fetchall()
    if orgs:
        products = conn.execute(sa.text("SELECT id, product_key FROM products")).fetchall()
        product_map = {p.product_key: p.id for p in products}
        
        insert_data = []
        now = datetime.datetime.utcnow()
        for org in orgs:
            if not org.entitlements:
                continue
            for key in org.entitlements:
                product_id = product_map.get(key)
                if product_id:
                    insert_data.append({
                        "id": uuid.uuid4(),
                        "organization_id": org.id,
                        "product_id": product_id,
                        "created_at": now
                    })
        if insert_data:
            meta = sa.MetaData()
            ent_table = sa.Table(
                'organization_entitlements', meta,
                sa.Column('id', sa.Uuid()),
                sa.Column('organization_id', sa.Uuid()),
                sa.Column('product_id', sa.Uuid()),
                sa.Column('created_at', sa.DateTime())
            )
            op.bulk_insert(ent_table, insert_data)

    op.drop_column('organizations', 'entitlements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('entitlements', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_organization_entitlements_product_id'), table_name='organization_entitlements')
    op.drop_index(op.f('ix_organization_entitlements_organization_id'), table_name='organization_entitlements')
    op.drop_table('organization_entitlements')
    # ### end Alembic commands ###
