"""cost_cents and action_id

Revision ID: 852f4ac09824
Revises: a962e66a7c69
Create Date: 2026-08-01 10:12:40.367810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852f4ac09824'
down_revision: Union[str, Sequence[str], None] = 'a962e66a7c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quota_check_requests', sa.Column('action_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_quota_check_requests_action_id'), 'quota_check_requests', ['action_id'], unique=False)
    op.create_foreign_key(None, 'quota_check_requests', 'quota_actions', ['action_id'], ['id'], ondelete='SET NULL')
    op.add_column('usage_ledger', sa.Column('cost_cents', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_ledger', 'cost_cents')
    op.drop_constraint(None, 'quota_check_requests', type_='foreignkey')
    op.drop_index(op.f('ix_quota_check_requests_action_id'), table_name='quota_check_requests')
    op.drop_column('quota_check_requests', 'action_id')
    # ### end Alembic commands ###
