"""add product_id to quota_action

Revision ID: a962e66a7c69
Revises: f323b6922761
Create Date: 2026-08-01 09:44:39.537517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a962e66a7c69'
down_revision: Union[str, Sequence[str], None] = 'f323b6922761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'action_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'result',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_audit_logs_member'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_org'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_member_id'), 'audit_logs', ['member_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'members', ['member_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_logs', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.alter_column('credit_ledger', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('credit_ledger', 'reference_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_credit_ledger_consume_idempotency'), table_name='credit_ledger', postgresql_where="((type = 'consume'::text) AND (reference_id IS NOT NULL))")
    op.drop_index(op.f('idx_credit_ledger_created'), table_name='credit_ledger')
    op.drop_index(op.f('idx_credit_ledger_org'), table_name='credit_ledger')
    op.create_index(op.f('ix_credit_ledger_organization_id'), 'credit_ledger', ['organization_id'], unique=False)
    op.drop_index(op.f('idx_invoice_line_items_invoice'), table_name='invoice_line_items')
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('invoices', 'external_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_invoices_org'), table_name='invoices')
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.alter_column('members', 'firebase_uid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('members', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('members', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_members_email'), table_name='members')
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=False)
    op.alter_column('organization_members', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_org_members_member'), table_name='organization_members')
    op.drop_index(op.f('idx_org_members_org'), table_name='organization_members')
    op.drop_constraint(op.f('organization_members_organization_id_member_id_key'), 'organization_members', type_='unique')
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_unique_constraint(None, 'organization_members', ['member_id'])
    op.alter_column('organization_quota_limits', 'period',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_org_quota_limits_action'), table_name='organization_quota_limits')
    op.drop_index(op.f('idx_org_quota_limits_org'), table_name='organization_quota_limits')
    op.drop_constraint(op.f('organization_quota_limits_organization_id_action_id_period_key'), 'organization_quota_limits', type_='unique')
    op.create_index(op.f('ix_organization_quota_limits_action_id'), 'organization_quota_limits', ['action_id'], unique=False)
    op.create_index(op.f('ix_organization_quota_limits_organization_id'), 'organization_quota_limits', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_organization_quota_limits_org_action_period', 'organization_quota_limits', ['organization_id', 'action_id', 'period'])
    op.drop_constraint(op.f('organization_quota_limits_action_id_fkey'), 'organization_quota_limits', type_='foreignkey')
    op.create_foreign_key(None, 'organization_quota_limits', 'quota_actions', ['action_id'], ['id'], ondelete='CASCADE')
    op.alter_column('organization_subscriptions', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_org_subs_org'), table_name='organization_subscriptions')
    op.drop_index(op.f('idx_org_subs_plan'), table_name='organization_subscriptions')
    op.create_index(op.f('ix_organization_subscriptions_organization_id'), 'organization_subscriptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_plan_id'), 'organization_subscriptions', ['plan_id'], unique=False)
    op.drop_index(op.f('idx_org_usage_lifetime_org'), table_name='organization_usage_lifetime')
    op.drop_constraint(op.f('organization_usage_lifetime_organization_id_action_id_key'), 'organization_usage_lifetime', type_='unique')
    op.create_index(op.f('ix_organization_usage_lifetime_organization_id'), 'organization_usage_lifetime', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_organization_usage_lifetime_org_action', 'organization_usage_lifetime', ['organization_id', 'action_id'])
    op.drop_constraint(op.f('organization_usage_lifetime_action_id_fkey'), 'organization_usage_lifetime', type_='foreignkey')
    op.create_foreign_key(None, 'organization_usage_lifetime', 'quota_actions', ['action_id'], ['id'], ondelete='CASCADE')
    op.alter_column('organizations', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('organizations', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('organizations', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('organizations', 'tier',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'starter'::text"))
    op.alter_column('organizations', 'billing_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'postpay'::text"))
    op.drop_index(op.f('idx_organizations_status'), table_name='organizations')
    op.create_index(op.f('ix_organizations_status'), 'organizations', ['status'], unique=False)
    op.alter_column('plans', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('plans', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::text"))
    op.alter_column('products', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('products', 'product_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_products_key'), table_name='products')
    op.drop_index(op.f('idx_quota_action_prices_action'), table_name='quota_action_prices')
    op.drop_index(op.f('idx_quota_action_prices_effective'), table_name='quota_action_prices')
    op.create_index(op.f('ix_quota_action_prices_action_id'), 'quota_action_prices', ['action_id'], unique=False)
    op.add_column('quota_actions', sa.Column('product_id', sa.Uuid(), nullable=True))
    op.alter_column('quota_actions', 'action_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('quota_actions', 'domain',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('quota_actions', 'unit_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('quota_actions', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_quota_actions_domain'), table_name='quota_actions')
    op.create_index(op.f('ix_quota_actions_domain'), 'quota_actions', ['domain'], unique=False)
    op.create_index(op.f('ix_quota_actions_product_id'), 'quota_actions', ['product_id'], unique=False)
    op.create_foreign_key(None, 'quota_actions', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('quota_check_requests', 'request_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('quota_check_requests', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'committed'::text"))
    op.alter_column('quota_check_requests', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_quota_check_requests_org'), table_name='quota_check_requests')
    op.drop_constraint(op.f('quota_check_requests_organization_id_request_id_key'), 'quota_check_requests', type_='unique')
    op.create_index(op.f('ix_quota_check_requests_organization_id'), 'quota_check_requests', ['organization_id'], unique=False)
    op.alter_column('super_admin_audit_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('super_admin_audit_logs', 'target_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('super_admin_audit_logs', 'detail',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_admin_audit_admin'), table_name='super_admin_audit_logs')
    op.drop_index(op.f('idx_admin_audit_created'), table_name='super_admin_audit_logs')
    op.create_index(op.f('ix_super_admin_audit_logs_admin_member_id'), 'super_admin_audit_logs', ['admin_member_id'], unique=False)
    op.create_index(op.f('ix_super_admin_audit_logs_created_at'), 'super_admin_audit_logs', ['created_at'], unique=False)
    op.alter_column('usage_ledger', 'unit_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('usage_ledger', 'request_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_usage_ledger_created'), table_name='usage_ledger')
    op.drop_index(op.f('idx_usage_ledger_org'), table_name='usage_ledger')
    op.drop_index(op.f('idx_usage_ledger_org_request_id'), table_name='usage_ledger', postgresql_where='(request_id IS NOT NULL)')
    op.create_index(op.f('ix_usage_ledger_organization_id'), 'usage_ledger', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_ledger_organization_id'), table_name='usage_ledger')
    op.create_index(op.f('idx_usage_ledger_org_request_id'), 'usage_ledger', ['organization_id', 'request_id'], unique=True, postgresql_where='(request_id IS NOT NULL)')
    op.create_index(op.f('idx_usage_ledger_org'), 'usage_ledger', ['organization_id'], unique=False)
    op.create_index(op.f('idx_usage_ledger_created'), 'usage_ledger', ['created_at'], unique=False)
    op.alter_column('usage_ledger', 'request_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usage_ledger', 'unit_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_super_admin_audit_logs_created_at'), table_name='super_admin_audit_logs')
    op.drop_index(op.f('ix_super_admin_audit_logs_admin_member_id'), table_name='super_admin_audit_logs')
    op.create_index(op.f('idx_admin_audit_created'), 'super_admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_admin_audit_admin'), 'super_admin_audit_logs', ['admin_member_id'], unique=False)
    op.alter_column('super_admin_audit_logs', 'detail',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('super_admin_audit_logs', 'target_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('super_admin_audit_logs', 'action',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_quota_check_requests_organization_id'), table_name='quota_check_requests')
    op.create_unique_constraint(op.f('quota_check_requests_organization_id_request_id_key'), 'quota_check_requests', ['organization_id', 'request_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_quota_check_requests_org'), 'quota_check_requests', ['organization_id'], unique=False)
    op.alter_column('quota_check_requests', 'reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('quota_check_requests', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'committed'::text"))
    op.alter_column('quota_check_requests', 'request_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'quota_actions', type_='foreignkey')
    op.drop_index(op.f('ix_quota_actions_product_id'), table_name='quota_actions')
    op.drop_index(op.f('ix_quota_actions_domain'), table_name='quota_actions')
    op.create_index(op.f('idx_quota_actions_domain'), 'quota_actions', ['domain'], unique=False)
    op.alter_column('quota_actions', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('quota_actions', 'unit_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('quota_actions', 'domain',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('quota_actions', 'action_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('quota_actions', 'product_id')
    op.drop_index(op.f('ix_quota_action_prices_action_id'), table_name='quota_action_prices')
    op.create_index(op.f('idx_quota_action_prices_effective'), 'quota_action_prices', ['effective_from'], unique=False)
    op.create_index(op.f('idx_quota_action_prices_action'), 'quota_action_prices', ['action_id'], unique=False)
    op.create_index(op.f('idx_products_key'), 'products', ['product_key'], unique=False)
    op.alter_column('products', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'product_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('plans', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::text"))
    op.alter_column('plans', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_organizations_status'), table_name='organizations')
    op.create_index(op.f('idx_organizations_status'), 'organizations', ['status'], unique=False)
    op.alter_column('organizations', 'billing_mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'postpay'::text"))
    op.alter_column('organizations', 'tier',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'starter'::text"))
    op.alter_column('organizations', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('organizations', 'slug',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'organization_usage_lifetime', type_='foreignkey')
    op.create_foreign_key(op.f('organization_usage_lifetime_action_id_fkey'), 'organization_usage_lifetime', 'quota_actions', ['action_id'], ['id'])
    op.drop_constraint('uq_organization_usage_lifetime_org_action', 'organization_usage_lifetime', type_='unique')
    op.drop_index(op.f('ix_organization_usage_lifetime_organization_id'), table_name='organization_usage_lifetime')
    op.create_unique_constraint(op.f('organization_usage_lifetime_organization_id_action_id_key'), 'organization_usage_lifetime', ['organization_id', 'action_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_org_usage_lifetime_org'), 'organization_usage_lifetime', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_organization_subscriptions_plan_id'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_organization_id'), table_name='organization_subscriptions')
    op.create_index(op.f('idx_org_subs_plan'), 'organization_subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('idx_org_subs_org'), 'organization_subscriptions', ['organization_id'], unique=False)
    op.alter_column('organization_subscriptions', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'organization_quota_limits', type_='foreignkey')
    op.create_foreign_key(op.f('organization_quota_limits_action_id_fkey'), 'organization_quota_limits', 'quota_actions', ['action_id'], ['id'])
    op.drop_constraint('uq_organization_quota_limits_org_action_period', 'organization_quota_limits', type_='unique')
    op.drop_index(op.f('ix_organization_quota_limits_organization_id'), table_name='organization_quota_limits')
    op.drop_index(op.f('ix_organization_quota_limits_action_id'), table_name='organization_quota_limits')
    op.create_unique_constraint(op.f('organization_quota_limits_organization_id_action_id_period_key'), 'organization_quota_limits', ['organization_id', 'action_id', 'period'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_org_quota_limits_org'), 'organization_quota_limits', ['organization_id'], unique=False)
    op.create_index(op.f('idx_org_quota_limits_action'), 'organization_quota_limits', ['action_id'], unique=False)
    op.alter_column('organization_quota_limits', 'period',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'organization_members', type_='unique')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.create_unique_constraint(op.f('organization_members_organization_id_member_id_key'), 'organization_members', ['organization_id', 'member_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_org_members_org'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('idx_org_members_member'), 'organization_members', ['member_id'], unique=False)
    op.alter_column('organization_members', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.create_index(op.f('idx_members_email'), 'members', ['email'], unique=False)
    op.alter_column('members', 'display_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('members', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('members', 'firebase_uid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.create_index(op.f('idx_invoices_org'), 'invoices', ['organization_id'], unique=False)
    op.alter_column('invoices', 'external_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.create_index(op.f('idx_invoice_line_items_invoice'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.drop_index(op.f('ix_credit_ledger_organization_id'), table_name='credit_ledger')
    op.create_index(op.f('idx_credit_ledger_org'), 'credit_ledger', ['organization_id'], unique=False)
    op.create_index(op.f('idx_credit_ledger_created'), 'credit_ledger', ['created_at'], unique=False)
    op.create_index(op.f('idx_credit_ledger_consume_idempotency'), 'credit_ledger', ['organization_id', 'reference_id'], unique=True, postgresql_where="((type = 'consume'::text) AND (reference_id IS NOT NULL))")
    op.alter_column('credit_ledger', 'reference_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('credit_ledger', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_member_id'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_org'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_member'), 'audit_logs', ['member_id'], unique=False)
    op.alter_column('audit_logs', 'result',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
