"""Add deliverables

Revision ID: c5b68a69b0a0
Revises: a1b2c3d4e5f6_harden_quota
Create Date: 2026-09-02 21:43:31.000185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b68a69b0a0'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6_harden_quota'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliverables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deliverable_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('products', sa.Column('deliverable_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_products_deliverable_id'), 'products', ['deliverable_id'], unique=False)
    op.create_foreign_key('fk_products_deliverables', 'products', 'deliverables', ['deliverable_id'], ['id'], ondelete='SET NULL')
    op.drop_column('products', 'product_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_products_deliverables', 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_deliverable_id'), table_name='products')
    op.drop_column('products', 'deliverable_id')
    op.drop_table('deliverables')
    # ### end Alembic commands ###
