"""add initial_credits to org invite

Revision ID: d4b5c6e7f8a9
Revises: 22e9491cdaee
Create Date: 2026-09-04 11:27:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b5c6e7f8a9'
down_revision: Union[str, Sequence[str], None] = '22e9491cdaee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_invites', sa.Column('initial_credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_invites', 'initial_credits')
    # ### end Alembic commands ###
